export const NAVIGATION_SIDEBAR_WIDTH = 60;
export const NAVIGATION_STRUCTURE_WIDTH = 300;
export const NAVIGATION_STRUCTURE_WIDTH_MAX = 420;
export const NAVIGATION_STRUCTURE_ANIMATION_DURATION = 1000;
export const NAVIGATION_HEADER_HEIGHT = 60;
export const NAVIGATION_HEADER_HEIGHT_HIGHEST = 108;
export const LAYOUT_MODE_LOCALSTORAGE_KEY = 'layoutMode';
export const LAYOUT_MODE_LOCALSTORAGE_KEY_SIZE = 'layoutResizer';
